### PR TITLE
pkgconfig fix

### PR DESCRIPTION
**Pull request by attuska**

### CODE REVIEW

**Comment by palinek** [comment]
@attuska 
please, change the log message to follow [wiki](https://github.com/lxde/lxqt/wiki/Contributing-code). That means log messages like described [here](http://chris.beams.io/posts/git-commit/).

**Comment by attuska** [comment]
I am not yet in a position to provide it.
In my opinion is that this is a bug in the code, but I do it rather just for myself in the future with patches.
I could not compile the code without this change.
But you konnt mistakes selbs resolved without me.
(Google translated)
I have deleted my fork,and closed PR.

**Comment by palinek** [comment]
I didn't intend neither to offend you nor to say that there is no bug. Just saw your recent conversations with @pmattern about git usage etc. (you seem to be reasonably skilled with git). Just wanted to point out the agreed wording for commit log messages in LXQt.

**Comment by attuska** [comment]
Very much!
I do not feel offended, but I must admit that I still have to learn a lot about git.
I verde my forks delete all except liblxqt and lxqt panel whose PR s are my opinion, GTM.
(Goggle translate from German, the much better than from Hungarian)

**Comment by palinek** [comment]
@attuska Just FYI. I've manualy reassembled your proposed commit and pushed it into master -> lxde/lxqt-globalkeys@6ccef92.

**Comment by attuska** [comment]
Thank you for taking me and apologize, I do not know many important things.
And I can already leave this fall patch: https://github.com/uhulinux/ub/blob/master/lxqt-globalkeys/patches/pkgconfig-fix.patch

**Pull request closed without merging**
