### PR TITLE
Updated german translation, make it common for all german speaking regio...

### PR DESCRIPTION
**Pull request by ThomasVie**
...ns.

### CODE REVIEW

**Comment by pmattern** [comment]
*lxqt-config-globalkeyshortcuts_de.desktop*
I think lines "GenericName" and "Comment" should be switched to keep things consistent with the English template.

*lxqt-config-globalkeyshortcuts_de.ts*
In line 12 I'd replace "Finde einen Befehl" with "Befehl finden". This would be neutral with regards to "Du" vs. "Sie" ("pronominale Anredeform" vs. "Höflichkeitsform").
In line 47 "Verwerfen" is actually wrong. This should be "Zurücksetzen".
Line 58: "Kein" as single word isn't possible in German. To make it better one had to know what this string is referring to. And the funny thing is I didn't achieve this. Which affects many other strings as well. So I wonder whether this translation file is referring to something that doesn't exist any longer. Yet I'd suggest to leave it as is for now.
In line 74 it should be "zurücksetzen" instead of "verwerfen", counterpart to line 47.
Recent lxqt-config-globalkeyshortcuts.ts comprises 16 additional lines at the end which are missing in lxqt-config-globalkeyshortcuts_de.ts.

**Comment by paulolieuthier** [comment]
@ThomasVie please, update this.

**Comment by ThomasVie** [comment]
I'll do it this evening.

**Comment by ThomasVie** [comment]
Squashed pull request.

**Comment by pmattern** [comment]
Landed in a5d135b and dcc21d2.

Thanks.

**Pull request closed without merging**
