### PR TITLE
[WIP] daemon: not grabbing disabled shortcuts

### PR DESCRIPTION
**Pull request by palinek**
fixes lxde/lxqt#618

### CODE REVIEW

**Comment by palinek** [comment]
...this is realy a raw piece of work and I'm not completely sure about all that stuff that's happening in the daemon.
Basicaly it's been working for me on scenarios i've used.

@kuzmas can you, please, have a look? Also for this `//TODO: (un)grab only after multiple usage check!?!` i will appreciate any suggestions.

thanks

**Comment by kuzmas** [comment]
I have added `mDisabledIdsByShortcut` to track disabled actions.
To track all actions for each shortcut there are 2 maps now: `mIdsByShortcut` and `mDisabledIdsByShortcut`. An action can be only in one of them. If it's enabled - it's in `mIdsByShortcut` otherwise in `mDisabledIdsByShortcut`.

With this it's easy to track whether it was the last action disabled for a shortcut (so we can release it) and it's the first action enabled so we need to re-grab the shortcut again.
P.S. I haven't tested it thoroughly, but at least it compiles ;-)

**Comment by palinek** [comment]
@paulolieuthier  can you have a look on this ... and test, please?

**Comment by paulolieuthier** [comment]
I will.

**Comment by paulolieuthier** [comment]
LGTM.

**Pull request merged**
